linters:
    - deadcode
    - dupl
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gotype
    - ineffassign
    - interfacer
    - lll
    - vet
    - vetshadow
skipdirs:
    - skip-dir
go: 1.6
vendor: false
