linters:
    - aligncheck
    - deadcode
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gotype
    - ineffassign
    - interfacer
    - lll
    - structcheck
    - test
    - testify
    - varcheck
    - vet
    - vetshadow
    - unconvert
skipdirs:
    - skip-dir
go: 1.6
vendor: false